name: Update POT

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pot-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache

      - name: Install NPM dependencies
        run: npm ci

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-cache

      - name: Install Composer dependencies
        run: composer install

      - name: Start WP Environment
        run: npm run env:start
    
      - name: Wait for WordPress to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8888 | grep -q "WordPress"; then
              echo "WordPress is ready";
              break;
            fi
            echo "Waiting for WordPress... ($i/30)";
            sleep 5;
          done

      - name: Generate POT
        run: |
          npx wp-env run cli --env-cwd='wp-content/plugins/wp-multisite-waas' \
          wp i18n make-pot . lang/multisite-ultimate.pot \
          --slug=multisite-ultimate \
          --exclude=node_modules,tests,docs,assets/js/lib

      - name: Check for changes
        id: git-check
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          FILE="wp-content/plugins/wp-multisite-waas/lang/multisite-ultimate.pot"
          if git ls-files --error-unmatch "$FILE" > /dev/null 2>&1; then
            if git diff --exit-code -- "$FILE"; then
                echo "no-changes=true" >> $GITHUB_OUTPUT
            else
                echo "no-changes=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "no-changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create PR if changed
        if: steps.git-check.outputs.no-changes == 'false'
        run: |
          BRANCH="chore/update-pot-file-$(date +%Y%m%d%H%M%S)"
          git checkout -b $BRANCH
          git add wp-content/plugins/wp-multisite-waas/lang/multisite-ultimate.pot
          git commit -m "Update POT file"
          git push origin $BRANCH
          gh pr create --title "Update POT file" --body "Auto-generated POT update" --head $BRANCH --base main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Stop WordPress Environment
        if: always()
        run: npm run env:stop
